### ISSUE TITLE
When I turn the block osu connection! Nothing happened

### ISSUE THREAD

**Issue by irution** [Koltay/osuEscape#2]
https://www.youtube.com/watch?v=Ji7vpL-VD1c&ab_channel=PungPuen

**Comment by Koltay** [comment]
After the investigation, the "osu block" firewall rule is not applied to the advanced firewall, will update the version when fixed.

**Comment by Koltay** [comment]
Conclusion: notavxx's osu! folder was named with space in it, will fix in the next version.
